### ISSUE TITLE
Feedback from initial usage

### ISSUE THREAD

**Issue by elrafoon** [t-industry/micrortu_sdk#1]
While implementing a heating controller, I came to this missing features:

1. [x] easily usable crate-wide allocator to alloc block instances
2. [ ] some entry-point function returning T or &mut T context
3. [ ] this context shall then be passed to factory functions (allocator could be passed this way too)
4. [x] ports! macro shall accept more then just plain struct (at least field comments), i.e.:
```rust
ports! {
    #[allow(non_snake_case)]
    pub struct Params {
        /// proportional gain
        Kp: In 1 1,
        /// integrator constant
        Ki: In 1 1,
        /// derivator constant
        Kd: In 1 1,
    }
}
```

5. [x] either Shared or ports! macro generated struct shall have some fill/set function, user can write:
```rust
shared.add_ports(Ports::report());
shared.add_params(Params::report());
```

instead of

```rust
let ports = Ports::report();
let params = Params::report();

shared.ports[..ports.len()].copy_from_slice(ports);
shared.used_ports_len = ports.len() as u32;
shared.params[..params.len()].copy_from_slice(params);
shared.used_params_len = params.len() as u32;
```

6. [ ] maybe add support for cargo-generate? https://github.com/cargo-generate/cargo-generate

**Comment by Ddystopia** [comment]
Done in 0.1.3
